### PR TITLE
rtl8189fs-mod: Add compatible machine orangepi-plus2e

### PR DESCRIPTION
**Pull request by ajlennon**
Signed-off-by: Alex J Lennon <ajlennon@dynamicdevices.co.uk>

### CODE REVIEW

**Comment by geomatsi** [comment]
Hi @ajlennon ,

Thanks for your patch. You may have noticed, that xradio driver has recently been accepted to https://github.com/linux-sunxi/meta-sunxi. So I plan to submit rtl8189fs-mod as well. Hopefully, there will be no need for additional layer.

Regards,
Sergey

**Comment by ajlennon** [comment]
Thanks @geomatsi - fingers crossed. That does seem the most straightforward option.

I have another patch here which enables monitor mode by default. It builds the driver and I can bring up a monitor mode device but I see no packets.

Have you or anybody had monitor mode working? In fact can  you comment at all on the overall reliability you see of the driver? Thanks!

**Comment by geomatsi** [comment]
Hi @ajlennon ,
I have never tried monitor mode on this wireless card. As for reliability, I guess it depends on your use-cases. For me it looks more or less ok, at least better than xradio on orange-pi-zero. I have been 3d-printing using octoprint on orange-pi-pc-plus board for quite a while without any issues. But I have to admit that wireless connection is not critical in this case: only web interface and  telegram bot. So run your own tests to check if it works for your usecases.

P.S. In current configuration rtl8189fs driver is too verbose. If you have a patch with correct compilation flag to make it less noisy, do not hesitate to send another PR :)

Regards,
Sergey

**Comment by ajlennon** [comment]
Hi Sergey,

I've done some testing and using iw to add a monitor type device to the phy doesn't appear to work (device appears but no packets are RxD or TxD).

However using iwconfig to change the type of the existing wlan0 adaptor to monitor does work

NB I've just got started with OctoPi on a RPi3B+ with a Creality CR10-S and I absolutely love it. Brilliant piece of work. In fact I'm donating to Gina Häußge via Patreon...

Cheers,

Alex

**Pull request merged**
